### ISSUE TITLE
[CHANGE] storage getting filled

### ISSUE THREAD

**Issue by mkeroppi** [rohanb10/snoozz-tab-snoozing#15]
## What would you like to change
option to increase "storage" size

## What would you like to see instead
option to increase "storage" size - it's limited to 5.24MB for me.

## What is your specific use case (if applicable)
Increase time to automatically delete tab.  The 5.24 MB is only enough for 7 days.

What does the storage store anyways?

## Which browser / OS do you use
Firefox/Windows

**Comment by rohanb10** [comment]
Snoozz uses local storage to save user prefs (0.1 - 0.3KB) and tab metadata(tab name, url, icon, snooze/wakeup times).

The 5.24MB size limit is imposed across all extensions (for local storage). Its actually been the limit since day 1 of this extension, but only recently has it become visualised in Snoozz. 

On average a snoozing tab is around 0.2-0.4KB, meaning you could have anywhere between 5000 - 15000 tabs saved in Snoozz. Snoozed windows are roughly the size of the number of tabs they contain.

Currently it is possible for certain tabs to be larger. For example, gmail uses dynamic favicons to show "unread email count" on top of the icon, so if you snooze a gmail tab it is very likely that the size could be 2KB+ - 10x larger than the average tab. 
This is obviously not ideal, and in a future update there will be a soft size limit of an individual tab by limiting the length of the icon and/or name of the tab. I plan to make apply these changes retroactively, so it would affect all previously snoozed tabs as well. This will all happen behind the scenes with no difference to any existing functionality or UI elements.

Could you let me know how much storage you are using? There are other solutions, like [unlimited storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#Unlimited_storage) that I could implement, but ideally I would like to avoid it.

**Comment by mkeroppi** [comment]
Actually I'm not sure what the "Automatically delete tabs after" option do.  After I reset it to 7 days the storage usage is now fine.  That seems to be what was taking up the storage.  Maybe more guidance on that could be better.

**Comment by rohanb10** [comment]
Updated the copy. Will be out with the next release
<img width="759" alt="Screenshot 2020-11-23 at 11 01 33 PM" src="https://user-images.githubusercontent.com/11708770/99995217-11d49200-2de0-11eb-8c8e-b8bd485f8408.png">

**Comment by rohanb10** [comment]
Updated in v2.3.2
