### ISSUE TITLE
[firefox] support for right-click tab menu

### ISSUE THREAD

**Issue by mkeroppi** [rohanb10/snoozz-tab-snoozing#2]
Can we have support for snoozing a tab from right-clicking a tab?

**Comment by rohanb10** [comment]
Are you referring to right click on a tab in the tab bar? As far as I know this isn't possible with the current WebExtension APIs. If you know of another extension that makes use of this could you please send me a link?

I would love to add this feature and I was quite disappointed to learn that it was not possible to do

**Comment by mkeroppi** [comment]
Snooze Tabs has it: https://addons.mozilla.org/en-US/firefox/addon/snoozetabs/
https://github.com/bwinton/SnoozeTabs

**Comment by rohanb10** [comment]
Will take a look. Thanks

**Comment by rohanb10** [comment]
So turns out there's [some discrepancies](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/ContextType) between Chrome (which I primarily use) and Firefox WebExtension APIs. Firefox supports the `tab` contextType and Chrome does not. 

I already have started making changes to include support for icons (FF only) + disabling invalid snooze times in the context menu. I will be sure to add this to right click menu soon.

**Comment by rohanb10** [comment]
Context Menu changes have just been pushed https://github.com/rohanb10/snoozz-tab-snoozing/commit/08ba9f5c6f346c6dda7e14351afb5dcdcbbc5cd4 (all FF only because chrome is dumb)

1. Allow clicking on tabs in tab bar to trigger contextMenu
2. Show icons next to menu items
3. Dynamically disable invalid options (eg. disable today morning if it is 5pm) 

Just need to do a bit more testing (to make sure I havent broken anything on chrome) and next release will be ready to go live

**Comment by rohanb10** [comment]
Bug has been fixed in v2.1.2
