### ISSUE TITLE
can't manually specify re-open date of 22nd of any month

### ISSUE THREAD

**Issue by DrunkenCommie** [rohanb10/snoozz-tab-snoozing#31]
## Description
Can't specify 22nd (of any month) as "Choose your own time". Tried 22 April, May, ...
Works just fine for 21st, 23rd.
Also - works just fine for 11th (so it's not "double digit entry issue").

## Expected Behavior
Be able to specify "open on 22.04" with "Choose your own time".

## Actual Behavior
After typing "22" - it just accepts first "2", then cursor jumps away to any other field (like "tomorrow" or "next week").

## How to Reproduce (if applicable)
Open any webpage, try to snooze it until 22.04, 22.05, 22.06, ... (22nd of any month)

## Your Device
* Browser and version: Firefox 88, Firefox 87
* OS: Windows 10
* Device Resolution (UI related bugs only) 3000x2000

## Which Page
Main Snooze Tab window.

## Screenshots / Videos / Logs
![obraz](https://user-images.githubusercontent.com/41784423/115578142-8d197180-a2b4-11eb-9f09-817b5c1446fc.png)

**Comment by rohanb10** [comment]
I had keyboard shortcuts for the numbers 1-8 to "highlight" the corresponding option in the popup. so when you type that out in the form it was triggering the shortcut. really dumb one, I should have caught it in testing. 

Anyway I have redesigned the "choose your own time" form and added a condition to specifically handle this case. Will be fixed in the next release
